### PR TITLE
fixed syntax error

### PR DESCRIPTION
**Pull request by JanWelker**
Looks like you accidental typed a pipe instead of a slash.

Cheers,
Jan

### CODE REVIEW

**Comment by xataz** [comment]
Hi,

It isn't an error, `${BASE_URL}` can contain one or more slash, so he use a pipe in delimiter for sed.
If he use a slash for this, `sed` couldn't differentiate the delimiter from slash of the URL.

Regards,
XataZ

**Comment by JanWelker** [comment]
Hi,

makes sense but does not seem to work:

echo base_url: False | sed -e "s|base_url : False|base_url : https://google.de|g"
base_url: False

sed --version
sed (GNU sed) 4.2.2

Are you guys using the OSX sed?

Cheers,
Jan

**Comment by Wonderfall** [comment]
I can confirm what @xataz said, I'm using pipe as delimiter since there are URLs.
I didn't try with macOS but we're using Alpine Linux and there's no issue with it. :)

**Comment by xataz** [comment]
it works : 
```shell
$ echo base_url : False | sed -e 's|base_url : False|base_url : https://google.de|g'
base_url : https://google.de
```

In your example, you have forgotten between base_url and :

**Comment by JanWelker** [comment]
My mistake. Thanks for the clarification.

**Pull request closed without merging**
