### PR TITLE
Add support to nextcloud image to use an S3 bucket as primary storage

### PR DESCRIPTION
**Pull request by rendhalver**

### CODE REVIEW

**Comment by Wonderfall** [comment]
Could it be documented?

**Comment by rendhalver** [comment]
Yep. Will do that once I get it working here.
I preemptively opened the PR before I got it working.

**Comment by rendhalver** [comment]
Actually we don't seem to be able to use autoconfig to setup S3.
I will see if I can work out another way to do it.

**Comment by rendhalver** [comment]
This isn't going to work with your how your image is setup.
I have discovered a different way to do it.
Closing this for now.

**Comment by js-mode** [comment]
How did you get it to work? I have been trying to do this myself with S3 and also Amazon-RDS postgresSQL. 

Did you find another image that you could make this work in?

**Comment by rendhalver** [comment]
I got it to work by adding an extra config file to the directory for the s3 settings.
It seems that you can do the same for other settings as needed.
When it started up it added those settings into the main config file.

**Comment by rendhalver** [comment]
@mode-js this has been reopened in #224

**Pull request closed without merging**
