### PR TITLE
Fix missing Redis

### PR DESCRIPTION
**Pull request by Berndinox**
https://github.com/Wonderfall/dockerfiles/issues/121

### CODE REVIEW

**Comment by Berndinox** [comment]
You can test die build with berndinox/nextcloud.
Also docker service scale is possible with php-redis, you just have to deploy a redis container within your stack and add the following part to your config:

```
   'memcache.distributed' => '\OC\Memcache\Redis',
   'memcache.locking' => '\OC\Memcache\Redis',
   'memcache.local' => '\OC\Memcache\APCu',
   'redis' => array(
     'host' => 'redis',
     'port' => 6379,
      ),

```

**Comment by Wonderfall** [comment]
Don't you get an error with `php7.1 -m`? I had the exact same Dockerfile, but it didn't work.

**Comment by Berndinox** [comment]
Nope, does work...
You can try my Image

**Comment by Wonderfall** [comment]
I can guarantee you it didn't work before, but now it seems it's working. 
Very strange (like computer science...). :/

**Pull request merged**
