### PR TITLE
Allows apps2 outside of root

### LINKED ISSUE #257: [ nextcloud ] ResourceLocator can not find a web root (root: /apps2/deck, file: XXX.css)
description:
After i set some apps, the page is very odd, because browser can't load correct css file.
What can i do to fix this?

info in nextcloud.log
>
**DECK**
{"reqId":"7Xq1Rob9MvJIm7p0iM8V","level":3,"time":"2017-10-27 11:24:05","remoteAddr":"MyDockerIP","user":"XXXX","app":"lib","method":"GET","url":"\/apps\/deck\/","message":"**ResourceLocator can not find a web root (root: \/apps2\/deck, file: css\/deck\/bd5e80ef07099242f7d93f8b4a31507e-style.css, webRoot: , throw: true)**","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.91 Safari\/537.36","version":"12.0.3.3"}
**contacts**
 {"reqId":"aqIfW2xO3acm083zzQlz","level":3,"time":"2017-10-27 11:43:25","remoteAddr":"MyDockerIP","user":"XXXXX","app":"lib","method":"GET","url":"\/apps\/contacts\/","message":"**ResourceLocator can not find a web root (root: \/apps2\/contacts, file: css\/contacts\/bd5e80ef07099242f7d93f8b4a31507e-style.css, webRoot: , throw: true)**","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.91 Safari\/537.36","version":"12.0.3.3"}

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #257 

I'm not a nginx expert. But this works on my dev env.

### CODE REVIEW

**Comment by hoellen** [comment]
I tried this on my environment, but I can't get it to run. 
My _apps2_ folder is at `/apps2/`
So I changed your `root /srv/http/;` to `root /;`
But I still get the error message and the css can't be load.
Why you choose the root location to `/srv/http/`? Can you give some help?

**Comment by skjnldsv** [comment]
@hoellen I'm an idiot, I forgot to edit! :) Let me check.

**Comment by hoellen** [comment]
@skjnldsv Thanks, but it still doesn't work for me. Works it with 12.0.3 or need I a special branch?

**Comment by skjnldsv** [comment]
@hoellen I added the basic solution used from a basic install, I don't use docker.
@Wonderfall will need to take a look.

**Comment by David-Development** [comment]
Thanks for working on this. I tried this solution but it doesn't work for me either. How is the nginx config going to solve the  "ResourceLocator can not find a web root" messages in nextcloud? I still receive the error messages in the log. However my browser does not show any urls that are not reachable. So I'm wondering if this is an issue that can be solved by reconfiguring the nginx or if this is something internally in the nextcloud server?

**Comment by skjnldsv** [comment]
Nginx can't serve a file outside of the webroot, so it's more than a nextcloud issue! :)

**Comment by mwlczk** [comment]
Hi, this didn't solve the problem for me.

**Pull request closed without merging**
